sudo: required

services:
  - docker

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t steasdal/ruby-node .
  - docker push steasdal/hello-world
  - docker images
